# include(joinpath("toolkit","runtests.jl"))
include(joinpath("geometric_center", "runtests.jl"))
# include(joinpath("distance", "runtests.jl"))
# include(joinpath("principal_axes","runtests.jl"))
# include(joinpath("angle","runtests.jl"))